services:
  - type: web
    name: gatornest-backend
    env: go
    buildCommand: cd cmd && go mod download && go build -o main
    startCommand: ./main
    envVars:
      - key: GIN_MODE
        value: release
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: gatornest-db
          property: connectionString
    plan: free

databases:
  - name: gatornest-db
    databaseName: gatornest
    user: gatornest
    plan: free 